#
# $Id$
#

SRC_TOP=..
TARGET_NAME=libusbmass
#Define ARMCPU! ARMCPU = lpc2478

OBJECT_FILES=mscbot.o mscscsi.o usbmass.o

INCLUDE_DIRS+=$(SRC_TOP)
include $(SRC_TOP)/make_rules/MakeRules

TARGETS=$(ARCHIVE_LIB)

all: $(TARGETS)
