#
# $Id$
#

SRC_TOP=..
TARGET_NAME=libshared
#Define ARMCPU! ARMCPU = lpc2478

OBJECT_FILES=eabi_compat.o platform.o

INCLUDE_DIRS+=$(SRC_TOP)
include $(SRC_TOP)/make_rules/MakeRules

TARGETS=$(ARCHIVE_LIB)

all: $(TARGETS)
