# $Id$
#
SRC_TOP=..

TARGET_NAME=catnb
OBJECT_FILES=main.o
TARGETS=$(TARGET_NAME)

INCLUDE_DIRS+=$(SRC_TOP)/shared
LDLIBS+=

override LDFLAGS+=

include $(SRC_TOP)/make_rules/MakeRules.usr

all: $(TARGETS)
