#
# $Id$
#

SRC_TOP=..
TARGET_NAME=libvirtdisk
#Define ARMCPU! ARMCPU = lpc2478

OBJECT_FILES=virtdisk.o virtfs.o

INCLUDE_DIRS+=$(SRC_TOP)
include $(SRC_TOP)/make_rules/MakeRules

TARGETS=$(ARCHIVE_LIB)

all: $(TARGETS)
